
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilwlliquljbgikgybbfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsd2xsaXF1bGpiZ2lrZ3liYmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjU4NjIsImV4cCI6MjA1OTI0MTg2Mn0.O1pEpoXG0UoO3RmxIy0QD78aZ4UVf-oViJk5ce4NNLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
